# Generated by Django 4.0.6 on 2022-07-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationCentre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=70, null=True, verbose_name='City')),
            ],
        ),
        migrations.AddField(
            model_name='vaccinationcentre',
            name='address',
            field=models.TextField(null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='vaccinationcentre',
            name='centre_name',
            field=models.CharField(max_length=60, null=True, verbose_name='Centre Name'),
        ),
        migrations.AddField(
            model_name='vaccinationcentre',
            name='pincode',
            field=models.IntegerField(null=True, verbose_name='Pin code'),
        ),
        migrations.AddField(
            model_name='vaccinationcentre',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccinationCentre.city'),
        ),
    ]
