# Generated by Django 4.0.6 on 2022-07-06 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaccinationCentre', '0002_city_vaccinationcentre_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('VaccinationCentre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccinationCentre.vaccinationcentre')),
            ],
        ),
    ]
