# Generated by Django 4.0.6 on 2022-07-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationCentre', '0005_bookings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='timeDate',
            field=models.DateTimeField(null=True),
        ),
    ]
