# Generated by Django 4.0.6 on 2022-07-06 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationCentre', '0009_bookings_timedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='timeDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 3, 27, 11, 98981), null=True),
        ),
    ]
